### ISSUE TITLE
OutOfRangeError - Word Index Exceeds Model's Maximum Limit

### ISSUE THREAD

**Issue by ipniel** [SirL0gic/TextAnalyser.js#1]
Issue Summary: 
When trying to predict sentiment for certain texts, the model threw an OutOfRangeError. This happened because some words in the input text had indices (after applying metadata.index_from offset) that exceeded the model's expected range of [0, 19999].

The error was triggered in the predictSentiment function where word indices were being set for the input tensor buffer. Some words had indices (after adjustments) that were out of bounds for the model's expectation.

How To Solve It:

1. When setting the word index in the buffer, ensure that it does not exceed the model's maximum limit.
2. Cap the index to a maximum value (in this case, 19999).
3. For words not found in metadata.word_index, set the index to a default value (e.g., 0).

```javascript
trimmed.forEach((word, i) => {
  if (metadata.word_index[word]) {
    let index = metadata.word_index[word];
    index = Math.min(index + metadata.index_from, 19999); // Cap the index
    inputBuffer.set(index, 0, i);
  } else {
    inputBuffer.set(0, 0, i);  // defaulting to 0 if word is not in metadata.word_index
  }
});
```

**Comment by SirL0gic** [comment]
Thank you. Patch is now implement in the V1.0.6.
